# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/wallpapers/garuda-wallpapers/garuda-wp-dessert-01.png'

# Special
background='#fcfcfc'
foreground='#22262A'
cursor='#fcfcfc'

# Colors
color0='#363A3E'
color1='#E28479'
color2='#47C3C5'
color3='#DFC266'
color4='#839AEC'
color5='#D18493'
color6='#78B3C5'
color7='#D2D2D4'
color8='#3C4044'
color9='#EC8E83'
color10='#51CDCF'
color11='#DFCC70'
color12='#8DA4F6'
color13='#DB8E9D'
color14='#82BDCF'
color15='#D1D1D3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
